
states.setEnterHandler("Idle", function() {})
states.addLoopHandler("Idle", function() {})
states.setExitHandler("Idle", function() {})
states.setChangeHandler(function() {})
states.matchCurrent(states.currentState())
states.matchNext(states.nextState())
states.matchNext(states.nextState())
states.debugOn()
states.setState("Idle")